name: Rust publish
on:
  release:
    types:
      - created
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo login
        run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Run build
        run: cargo build --package tapo --release --verbose
      - name: Run cargo publish
        run: cargo publish --package tapo
